[package]
name = "bevy-hands-on"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["hello_bevy", "my_library"]

[workspace.dependencies]
bevy = { version = "0.15", features = ["wayland"] }

[dependencies]
bevy.workspace = true
