[package]
name = "bevy-hands-on"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["hello_bevy", "my_library", "pig"]

[workspace.dependencies]
bevy = { version = "0.16", features = ["wayland"] }
bevy_egui = "0.34.1"

[dependencies]
bevy.workspace = true
